version: "3.4"

services:
  caddy:
    image: ghcr.io/ghost-brigade/sancartonfix-caddy:latest
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./api/public/images/media:/srv/app/public/images/media
      - caddy_data:/data
      - caddy_config:/config
      - caddy_log:/var/log/caddy
      - php_socket:/var/run/php
    environment:
      #PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 443
        published: 8443
        protocol: udp

  php:
    image: ghcr.io/ghost-brigade/sancartonfix-php:latest
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - php_socket:/var/run/php
      - .env:/srv/app/.env
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    restart: unless-stopped
    
volumes:
  caddy_data:
  caddy_config:
  caddy_log:
  db_data:
  php_socket:
  pgadmin:

