version: "3.4"

services:
  caddy:
    image: ghcr.io/ghost-brigade/sancartonfix-caddy:latest
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - caddy_log:/var/log/caddy
      - php_socket:/var/run/php
    environment:
      #PWA_UPSTREAM: pwa:3000
      SERVER_NAME: api.sancartonfix.mimso.net, caddy:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  php:
    image: ghcr.io/ghost-brigade/sancartonfix-php:latest
    restart: unless-stopped
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://app:password@database:3306/app}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^sancartonfix.mimso.net|api.sancartonfix.mimso.net|localhost|caddy$$
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://api.sancartonfix.mimso.net/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-app}

volumes:
  caddy_data:
  caddy_config:
  caddy_log:
  db_data:
  php_socket:

