version: "3.4"

services:
  caddy:
    image: ghcr.io/ghost-brigade/sancartonfix-caddy:latest
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - caddy_log:/var/log/caddy
      - php_socket:/var/run/php
    environment:
      #PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  php:
    image: ghcr.io/ghost-brigade/sancartonfix-php:latest
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - php_socket:/var/run/php
      - .env:/srv/app/.env
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-app}

volumes:
  caddy_data:
  caddy_config:
  caddy_log:
  db_data:
  php_socket:

