api_platform:
    title: SanCartonFix APIs
    version: 1.0.0
    show_webby: false
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
        pagination_items_per_page: 20
        collection:
            pagination:
                items_per_page_parameter_name: itemsPerPage
            
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
