vich_uploader:
    db_driver: orm

    mappings:
        media:
            uri_prefix: /images/media
            upload_destination: '%kernel.project_dir%/public/images/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
