controllers:
    resource: ../src/Controller/
    type: attribute

authentication_token:
    path: /authentication_token
    methods: ['POST']

profile:
    path: /profile
    methods: ['GET']

coop_tilleuls_forgot_password:
    resource: .
    type: coop_tilleuls_forgot_password
    prefix: '/forgot_password'
