name: Build and Push Caddy Docker Image

on:
  workflow_call: ~
  workflow_dispatch: ~

defaults:
  run:
    working-directory: ./api

jobs:
  build-caddy:
    name: Build and Push Caddy Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      
      - uses: docker/build-push-action@v3
        with:
          context: api
          target: app_caddy
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ secrets.GH_REPO }}-caddy:latest
          push: true
          cache-from: type=gha,scope=ghcr.io/${{ secrets.GH_REPO }}-caddy
          cache-to: type=gha,scope=ghcr.io/${{ secrets.GH_REPO }}-caddy,mode=max
        