name: Azure VM Update

on:
  workflow_dispatch: ~
  workflow_call: ~

env:
  ansible_path: ./ansible
  
jobs:
  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}
          ssh-host: ${{secrets.AZURE_VM_IP}}

      - name: Install docker and docker compose
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: docker/main.yml
          directory: ${{ env.ansible_path }}
          key: ${{secrets.AZURE_SSH_KEY}}
          inventory: |
            [all]
            ${{ secrets.AZURE_VM_IP }} ansible_user=${{ secrets.AZURE_SSH_USER }}
            
            [azure_vm:vars]
            ansible_python_interpreter=/usr/bin/python3
            
      - name: Update docker compose image
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: azure-vm-update.yml
          directory: ${{ env.ansible_path }}
          key: ${{secrets.AZURE_SSH_KEY}}
          options:
            --extra-vars gh_repo=${{ secrets.GH_REPO }} 
            --extra-vars azure_vm_user=${{ secrets.AZURE_SSH_USER }}
            --extra-vars env_content=${{ secrets.ENV_CONTENT }}
          inventory: |
            [all]
            ${{ secrets.AZURE_VM_IP }} ansible_user=${{ secrets.AZURE_SSH_USER }}
            
            [azure_vm:vars]
            ansible_python_interpreter=/usr/bin/python3
