name: Tests PHP

on:
  workflow_call: ~
  workflow_dispatch: ~
  push:
    branches:
      - '*'
      - '!master'

defaults:
  run:
    working-directory: ./api
    
jobs:
  tests:
    name: Tests - Unit & Integration
    runs-on: ubuntu-latest
    steps:
 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer:v2
          extensions: opcache, mbstring, exif, zip, xml, ctype, amqp, iconv, json, mbstring, pdo
        env:
          update: true

      - name: Check PHP Version
        run: php -v
        
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: PHPUnit
        run: php bin/phpunit
        
      - name: Doctrine Schema Validator
        run: php bin/console doctrine:schema:validate --skip-sync
      
      
      
