name: Tests Frontend

on:
  workflow_call: ~
  workflow_dispatch: ~
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - 'front/**'
      - '.github/workflows/tests-vue.yml'

defaults:
  run:
    working-directory: ./front

jobs:
  tests:
    name: Tests - Frontend
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
    
    - name: Lint
      continue-on-error: true
      run: npm run lint
