name: Tests PHP

on:
  workflow_call: ~
  workflow_dispatch: ~
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - 'api/**'
      - '.github/workflows/tests-php.yml'

defaults:
  run:
    working-directory: ./api

env:
  php_version: 8.1

jobs:
  tests:
    name: Tests - Backend
    runs-on: ubuntu-latest
    steps:
 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          coverage: none
          tools: composer:v2
          extensions: opcache, mbstring, exif, zip, xml, ctype, amqp, iconv, json, mbstring, pdo
        env:
          update: true

      - name: Check PHP Version
        run: php -v
        
      - name: Validate composer.json and composer.lock
        run: composer validate
          
      - name: Install Composer dependencies
        run: composer install
      - name: Pull images
        run: docker compose pull --ignore-pull-failures || true
      - name: Start services
        run: docker compose up --build -d
      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy)
                docker compose ps
                docker compose logs
                exit 1
              ;;
            esac
          done
          exit 1
      - name: Doctrine Schema Validator
        run: docker compose exec -T php bin/console doctrine:schema:validate --skip-sync
      - name: Create test database
        run: |
          docker compose exec -T php bin/console lexik:jwt:generate-keypair --skip-if-exists
          docker compose exec -T php bin/console -e test doctrine:database:create
          docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
          docker compose exec -T php bin/console -e test doctrine:fixtures:load --no-interaction
      - name: PHPUnit
        continue-on-error: true
        run: docker compose exec -T php bin/phpunit tests 
